# Generated by Django 3.1.5 on 2021-01-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя категории')),
                ('slug', models.SlugField()),
                ('is_published', models.BooleanField(default=True, verbose_name='Категория опубликована')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Имя товара')),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('is_weight', models.BooleanField(default=False, verbose_name='Весовой товар')),
                ('is_published', models.BooleanField(default=True, verbose_name='Категория опубликована')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productsapp.category')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['price', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.product')),
            ],
        ),
    ]
